// All packages, creators and SOL prices below are sample data.
// Nothing here is available for purchase.
export const skillCategories = ["Data export", "Developer tools", "Data workflows"];

export const skillExamples = {
  wallet: {
    slug: "wallet-history-to-csv",
    title: "Wallet history to CSV",
    category: "Data export",
    summary: "From transfer records to a tidy spreadsheet.",
    price: 0.08,
    creator: "Reusable Studio",
    description:
      "Give supported transfer records a useful shape. This example workflow organizes wallet activity into a structured export your agent can work with.",
    input: "A Solana wallet address and supported transfer records.",
    output: "A structured CSV export.",
    whatItDoes: [
      "Organizes supplied Solana transfer records into consistent columns.",
      "Includes timestamps, transaction IDs, token amounts and direction.",
      "Flags incomplete records for review before export.",
    ],
    requirements: [
      "An agent that can follow Markdown instructions and write CSV files.",
      "Transfer records you provide as JSON; this sample does not fetch live data.",
      "A wallet address to identify incoming and outgoing transfers.",
    ],
    exampleInput: '{\n  "wallet": "SAMPLE_WALLET",\n  "transfers": [\n    { "id": "sample_tx_01", "date": "2026-09-01", "amount": 1.25, "token": "SOL", "to": "SAMPLE_WALLET" }\n  ]\n}',
    exampleOutput: "date,transaction_id,token,amount,direction\n2026-09-01,sample_tx_01,SOL,1.25,incoming",
    color: "lavender",
    icon: "wallet",
  },
  api: {
    slug: "api-pagination-helper",
    title: "API pagination helper",
    category: "Developer tools",
    summary: "Every page, collected into one dataset.",
    price: 0.05,
    creator: "Pagewise Lab",
    description:
      "A reusable starting point for moving through a supported API’s pages, collecting the records and keeping them together.",
    input: "A supported paginated API endpoint and its configuration.",
    output: "Collected records in one dataset.",
    whatItDoes: [
      "Follows a next-page URL until the supplied API has no pages left.",
      "Collects results into a single list with a page count.",
      "Stops and reports errors instead of silently skipping a failed page.",
    ],
    requirements: [
      "An agent with an HTTP request tool or a JavaScript runtime with fetch.",
      "An API that returns items and a next-page URL.",
      "Your own API access and permission to read the requested records.",
    ],
    exampleInput: '{\n  "endpoint": "https://api.example.com/items",\n  "itemsKey": "items",\n  "nextPageKey": "next"\n}',
    exampleOutput: '{\n  "items": [{ "id": 1 }, { "id": 2 }, { "id": 3 }],\n  "pagesCollected": 2\n}',
    color: "blue",
    icon: "api",
  },
  csv: {
    slug: "csv-cleanup-workflow",
    title: "CSV cleanup workflow",
    category: "Data workflows",
    summary: "Consistent columns. Duplicates accounted for.",
    price: 0.06,
    creator: "Tableworks",
    description:
      "Make a messy table easier to use. This example workflow standardizes headings and flags duplicate rows for review.",
    input: "A CSV with inconsistent headings or duplicates.",
    output: "Standardized columns and flagged duplicate rows.",
    whatItDoes: [
      "Trims whitespace and converts headings to consistent snake_case names.",
      "Flags exact duplicate rows while preserving the source file.",
      "Produces a cleaned table and a short report of changes.",
    ],
    requirements: [
      "An agent that can read and write UTF-8 CSV files.",
      "A CSV with a header row and a consistent delimiter.",
      "A separate output location so the original file stays available.",
    ],
    exampleInput: "Full Name, Email\n Ada Lane ,ada@example.com\n Ada Lane ,ada@example.com",
    exampleOutput: "full_name,email,duplicate_flag\nAda Lane,ada@example.com,false\nAda Lane,ada@example.com,true",
    color: "peach",
    icon: "csv",
  },
  json: {
    slug: "json-to-table",
    title: "JSON to table",
    category: "Data export",
    summary: "Turn nested records into readable rows.",
    price: 0.04,
    creator: "Reusable Studio",
    description: "A sample workflow for flattening a list of JSON records into a table. Choose the fields you need and keep missing values visible.",
    whatItDoes: ["Maps selected JSON fields into named columns.", "Leaves missing values blank and lists them in a report."],
    requirements: ["An agent that can read JSON and write CSV.", "A JSON array of objects and a list of field paths."],
    exampleInput: '[{ "name": "Ada", "team": { "name": "Design" } }]',
    exampleOutput: "name,team_name\nAda,Design",
    color: "lavender",
    icon: "csv",
  },
  release: {
    slug: "release-notes-draft",
    title: "Release notes draft",
    category: "Developer tools",
    summary: "A clear first draft from a change list.",
    price: 0.07,
    creator: "Pagewise Lab",
    description: "Turn supplied commit summaries into a readable release-note draft. This sample groups changes by purpose and leaves the final review with you.",
    whatItDoes: ["Groups changes into additions, fixes and maintenance.", "Rewrites technical summaries into short reader-facing notes.", "Marks ambiguous changes for human review."],
    requirements: ["An agent that can follow Markdown instructions.", "A list of changes and the intended release version.", "A human reviewer to check the draft before publication."],
    exampleInput: "Version: 0.2.0\n- Add search to the skills list\n- Fix mobile card overflow",
    exampleOutput: "# Version 0.2.0\n\n## Added\n- Search skills by title or description.\n\n## Fixed\n- Skill cards fit narrow mobile screens.",
    color: "blue",
    icon: "api",
  },
  columns: {
    slug: "column-mapping-guide",
    title: "Column mapping guide",
    category: "Data workflows",
    summary: "Match source headings to your next table.",
    price: 0.03,
    creator: "Tableworks",
    description: "A sample guide for proposing a mapping between two table schemas. It calls out uncertain matches so you can review them before changing any data.",
    whatItDoes: ["Proposes field matches using supplied headings and descriptions.", "Flags uncertain or unmatched columns.", "Produces a mapping plan for review without editing the source."],
    requirements: ["An agent that can read table headings and field descriptions.", "Source and destination schemas.", "A reviewer to approve uncertain mappings."],
    exampleInput: 'Source: ["Full Name", "Email Address"]\nDestination: ["name", "email"]',
    exampleOutput: '{\n  "Full Name": "name",\n  "Email Address": "email"\n}',
    color: "peach",
    icon: "csv",
  },
};
